# Generated by Django 5.2.1 on 2025-06-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0006_additional_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], max_length=16),
        ),
    ]
