# Generated by Django 5.2.1 on 2025-06-08 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0010_remove_client_city_remove_client_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE VIEW user_tickets_view AS
                SELECT
                    o.id AS order_id,
                    o.client_id AS user_id,
                    o.status AS order_status,
                    o.updated_at,
                    t.id AS ticket_id,
                    t.event_id,
                    t.seat,
                    t.status AS ticket_status
                FROM orders o
                JOIN tickets t ON o.ticket_id = t.id
                WHERE o.status = 'completed';
            """,
            reverse_sql="DROP VIEW IF EXISTS user_tickets_view;"
        )
    ]
